# Generated by Django 4.2.1 on 2023-08-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='tag_name',
        ),
        migrations.AddField(
            model_name='tag',
            name='tags_count',
            field=models.IntegerField(default=0, verbose_name='Number of tags'),
        ),
    ]
